// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp_d-s84Y49ikzATAp19ZyKo8a7OuLg_8',
    appId: '1:138124502084:web:4dea8b2f3a31c93b010811',
    messagingSenderId: '138124502084',
    projectId: 'sispus-a9c3a',
    authDomain: 'sispus-a9c3a.firebaseapp.com',
    storageBucket: 'sispus-a9c3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYSAsrLm00JO3pI_9uwRRi0-CyTAC6Q-Y',
    appId: '1:138124502084:android:90d81f218535558d010811',
    messagingSenderId: '138124502084',
    projectId: 'sispus-a9c3a',
    storageBucket: 'sispus-a9c3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32XgbRiaAPBwxSzYn_zRH4ba-UPQQLos',
    appId: '1:138124502084:ios:d8735b9964305956010811',
    messagingSenderId: '138124502084',
    projectId: 'sispus-a9c3a',
    storageBucket: 'sispus-a9c3a.firebasestorage.app',
    iosBundleId: 'com.example.sispusMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32XgbRiaAPBwxSzYn_zRH4ba-UPQQLos',
    appId: '1:138124502084:ios:d8735b9964305956010811',
    messagingSenderId: '138124502084',
    projectId: 'sispus-a9c3a',
    storageBucket: 'sispus-a9c3a.firebasestorage.app',
    iosBundleId: 'com.example.sispusMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp_d-s84Y49ikzATAp19ZyKo8a7OuLg_8',
    appId: '1:138124502084:web:33b9fcd7c869980a010811',
    messagingSenderId: '138124502084',
    projectId: 'sispus-a9c3a',
    authDomain: 'sispus-a9c3a.firebaseapp.com',
    storageBucket: 'sispus-a9c3a.firebasestorage.app',
  );
}
